# Generated by Django 4.2.9 on 2026-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='major_category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=20),
        ),
    ]
